/**
 * Seed vocabulary for the couples games — English locale.
 *
 * Mirrors the structure of `ru.ts`: coherent scenario frames whose slots
 * cross into hundreds of imaginable situations. The `who` patterns complete
 * "Which of us would …?", the `norm` patterns read as card statements.
 */

import type { AxesByTheme, FramesByTheme, ScenarioFrame } from "./types";

/** Ways to sleep — manner, not location, so "cuddled up" can't end up under "keep". */
const HOME_CONDITIONS: readonly string[] = [
  "cuddled up",
  "in socks",
  "under two blankets",
  "with the window open",
  "on your own half",
  "on an air mattress",
  "under a throw blanket",
  "with the light on",
  "with music on",
  "at the edge of the bed",
  "in a sleeping bag",
  "to the sound of rain",
  "without a pillow",
  "in someone else's house",
  "outdoors",
  "cuddled up with the cat",
];

/** Real places, for frames that need a prepositional location. */
const HOME_LOCATIONS: readonly string[] = [
  "on the floor",
  "on the balcony",
  "in the kitchen",
  "on the couch",
  "in the wardrobe",
  "in the country house",
  "in a tent",
  "on the windowsill",
  "against the wall",
  "on the top shelf",
  "in the garage",
  "under the bed",
  "in the storage closet",
  "in the hallway",
  "in the attic",
  "in the bathroom",
];

export const FRAMES: FramesByTheme = {
  home: [
    {
      norm: "To sleep {a}",
      who: "rather fall asleep {a}",
      a: HOME_CONDITIONS,
    },
    {
      norm: "To keep {a} {b}",
      who: "rather keep {a} {b}",
      a: [
        "plastic bags",
        "mugs",
        "phone chargers",
        "socks",
        "books",
        "cardboard boxes",
        "blankets",
        "tools",
        "old photos",
        "spices",
        "slippers",
        "candles",
        "old receipts",
        "string lights",
        "pillows",
      ],
      b: HOME_LOCATIONS,
    },
    {
      norm: "To watch {a} {b}",
      who: "rather watch {a} {b}",
      a: [
        "series",
        "horror movies",
        "football",
        "the news",
        "cartoons",
        "cat videos",
        "reviews",
        "movies",
        "shows",
        "documentaries",
        "streams",
        "videos",
      ],
      b: [
        "before bed",
        "at dinner",
        "on weekends",
        "in the morning",
        "in bed",
        "under a blanket",
        "while cuddling",
        "at breakfast",
        "at night",
        "on the road",
      ],
    },
  ],

  romance: [
    {
      norm: "To hug {a}",
      who: "rather hug you {a}",
      a: [
        "in bed",
        "in the kitchen",
        "on the couch",
        "on a walk",
        "at the movies",
        "in the park",
        "at sunset",
        "in the rain",
        "on a rooftop",
        "in the car",
        "in a queue",
        "at the bus stop",
        "in the elevator",
        "on the beach",
        "in a café",
        "at home",
      ],
    },
    {
      norm: "To give {a} {b}",
      who: "rather give you {a} {b}",
      a: [
        "flowers",
        "plush toys",
        "jewelry",
        "greeting cards",
        "books",
        "perfume",
        "sweets",
        "movie tickets",
        "printed socks",
        "a photo album",
        "candles",
        "breakfast in bed",
      ],
      b: [
        "for an anniversary",
        "for no reason",
        "on a date",
        "on a birthday",
        "for New Year's",
        "on a first date",
        "just because",
        "on a Monday",
        "after a fight",
        "at sunset",
        "in front of the parents",
        "on vacation",
        "in the kitchen",
        "in the rain",
        "in bed",
      ],
    },
    {
      norm: "To confess love {a}",
      who: "rather confess love {a}",
      a: [
        "at sunset",
        "on a rooftop",
        "in the rain",
        "at dinner",
        "on a first date",
        "over the phone",
        "in a text message",
        "in public",
        "on vacation",
        "before bed",
        "in the kitchen",
        "in the park",
      ],
    },
    {
      norm: "To watch {a} together",
      who: "rather watch {a} together",
      a: [
        "rom-coms",
        "tearjerkers",
        "the sunset",
        "the stars",
        "the sunrise",
        "old photos",
        "series",
        "movies",
        "the moon",
        "the city from a rooftop",
        "the rain",
        "fireworks",
      ],
    },
    {
      norm: "To arrange {a} {b}",
      who: "rather arrange {a} {b}",
      a: [
        "a date",
        "a picnic",
        "dinner",
        "a surprise",
        "a photo shoot",
        "a walk",
        "an evening in",
        "a celebration",
        "some romance",
        "a day off",
      ],
      b: [
        "by candlelight",
        "under the open sky",
        "at home",
        "on a Friday",
        "for no reason",
        "on a rooftop",
        "by the sea",
        "in the park",
        "in front of friends",
        "in the rain",
      ],
    },
  ],

  habits: [
    {
      norm: "To eat {a} {b}",
      who: "rather eat {a} {b}",
      a: [
        "oatmeal",
        "fried eggs",
        "a sandwich",
        "porridge",
        "cottage cheese pancakes",
        "toast",
        "yogurt",
        "an omelet",
        "a croissant",
        "granola",
        "pancakes",
        "cottage cheese",
      ],
      b: [
        "every morning",
        "before bed",
        "for breakfast",
        "at lunch",
        "late at night",
        "on Mondays",
        "on weekends",
        "in bed",
        "on the run",
        "at the computer",
      ],
    },
    {
      norm: "To listen to {a} {b}",
      who: "rather listen to {a} {b}",
      a: [
        "one song",
        "podcasts",
        "the radio",
        "the news",
        "music",
        "audiobooks",
        "rain sounds",
        "jazz",
        "lectures",
        "silence",
        "a favorite song",
        "white noise",
      ],
      b: [
        "on repeat",
        "before bed",
        "in the shower",
        "on the road",
        "while working",
        "on a walk",
        "every day",
        "in headphones",
        "in the kitchen",
        "in the morning",
      ],
    },
    {
      norm: "To fall asleep {a}",
      who: "rather fall asleep {a}",
      a: [
        "to a podcast",
        "with the phone",
        "with the light on",
        "in socks",
        "while cuddling",
        "in the early hours",
        "on the couch",
        "under a blanket",
        "with the window open",
        "to music",
        "on the floor",
        "in someone else's house",
      ],
    },
    {
      norm: "To check {a} {b}",
      who: "rather check {a} {b}",
      a: [
        "the door",
        "the iron",
        "the stove",
        "the phone",
        "the lock",
        "the lights",
        "the gas",
        "the window",
        "the keys",
        "the alarm",
      ],
      b: [
        "three times",
        "before bed",
        "before leaving",
        "in the morning",
        "every evening",
        "on the road",
        "twice",
        "out of habit",
        "in a hurry",
        "in the dark",
      ],
    },
  ],

  food: [
    {
      norm: "To eat {a} with {b}",
      who: "rather eat {a} with {b}",
      a: [
        "pizza",
        "borscht",
        "soup",
        "pancakes",
        "pasta",
        "an omelet",
        "a burger",
        "shawarma",
        "sushi rolls",
        "porridge",
        "dumplings",
        "potatoes",
        "salad",
        "toast",
      ],
      b: [
        "pineapple",
        "chocolate",
        "ketchup",
        "mayonnaise",
        "condensed milk",
        "banana",
        "cheese",
        "jam",
        "mustard",
        "sour cream",
        "garlic",
        "honey",
        "bacon",
        "pickles",
        "a fried egg",
      ],
    },
    {
      norm: "To order {a} {b}",
      who: "rather order {a} {b}",
      a: [
        "pizza",
        "sushi",
        "burgers",
        "shawarma",
        "pasta",
        "sushi rolls",
        "dessert",
        "coffee",
        "borscht",
        "dumplings",
        "french fries",
        "a smoothie",
      ],
      b: [
        "late at night",
        "every evening",
        "into bed",
        "to work",
        "in the rain",
        "on weekends",
        "instead of cooking",
        "after the gym",
        "for a train ride",
        "for a date",
      ],
    },
    {
      norm: "To cook {a} {b}",
      who: "rather cook {a} {b}",
      a: [
        "breakfast",
        "dinner",
        "borscht",
        "pizza",
        "pasta",
        "an omelet",
        "pancakes",
        "soup",
        "salad",
        "a cake",
        "pilaf",
        "potatoes",
      ],
      b: [
        "together",
        "for the whole week",
        "from an internet video",
        "from mom's recipe",
        "at midnight",
        "for everyone",
        "without a recipe",
        "in a rush",
        "with guests over",
        "in a bad mood",
      ],
    },
    {
      norm: "To drink {a} {b}",
      who: "rather drink {a} {b}",
      a: [
        "coffee",
        "tea",
        "soda",
        "a smoothie",
        "cocoa",
        "water",
        "wine",
        "milk",
        "fruit drink",
        "an energy drink",
      ],
      b: [
        "before bed",
        "with milk",
        "at work",
        "in bed",
        "every day",
        "with cookies",
        "on an empty stomach",
        "late at night",
        "in the heat",
        "at breakfast",
      ],
    },
  ],

  money: [
    {
      norm: "To spend {a} on {b}",
      who: "rather spend {a} on {b}",
      a: [
        "a salary",
        "a bonus",
        "savings",
        "vacation pay",
        "the last money",
        "a stipend",
        "cashback",
        "gift money",
        "small change",
        "a secret stash",
      ],
      b: [
        "a trip",
        "gadgets",
        "clothes",
        "presents",
        "coffee",
        "taxis",
        "video games",
        "furniture",
        "books",
        "food",
        "cosmetics",
        "experiences",
      ],
    },
    {
      norm: "To save {a} for {b}",
      who: "rather save {a} for {b}",
      a: ["money", "coins", "cash", "banknotes", "cashback", "tips", "change", "bonuses"],
      b: [
        "a house",
        "a car",
        "a trip",
        "a wedding",
        "renovation",
        "education",
        "a pet",
        "a country house",
        "a business",
        "a dream",
      ],
    },
    {
      norm: "To buy {a} {b}",
      who: "rather buy {a} {b}",
      a: [
        "clothes",
        "gadgets",
        "books",
        "plants",
        "dishes",
        "candles",
        "toys",
        "board games",
        "coffee",
        "sweets",
        "socks",
        "furniture",
      ],
      b: [
        "on sale",
        "at the last moment",
        "for no reason",
        "in secret",
        "on credit",
        "once a year",
        "instead of food",
        "at a discount",
        "in an expensive store",
        "secondhand",
      ],
    },
    {
      norm: "To argue about {a} {b}",
      who: "rather argue about {a} {b}",
      a: [
        "the bill",
        "the price",
        "the tip",
        "the budget",
        "a purchase",
        "spending",
        "a piggy bank",
        "a discount",
        "a loan",
        "a subscription",
      ],
      b: [
        "in a café",
        "on vacation",
        "in a store",
        "at home",
        "in front of friends",
        "before payday",
        "at the checkout",
        "after the purchase",
        "online",
        "on the way home",
      ],
    },
  ],

  travel: [
    {
      norm: "To go {a} {b}",
      who: "rather go {a} {b}",
      a: [
        "to the sea",
        "to the mountains",
        "to another city",
        "to the country house",
        "to the village",
        "abroad",
        "to an island",
        "to the forest",
        "to Europe",
        "up north",
        "on vacation",
        "to grandma's",
      ],
      b: [
        "in winter",
        "in summer",
        "without a plan",
        "just the two of us",
        "with a tent",
        "by train",
        "by car",
        "hitchhiking",
        "for the weekend",
        "for a month",
        "with kids",
        "without money",
      ],
    },
    {
      norm: "To pack {a} {b}",
      who: "rather pack {a} {b}",
      a: [
        "a suitcase",
        "a backpack",
        "a first-aid kit",
        "clothes",
        "road snacks",
        "a blanket",
        "books",
        "presents",
        "a swimsuit",
        "a warm sweater",
      ],
      b: [
        "the night before the flight",
        "at the last moment",
        "from a list",
        "a month ahead",
        "in a hurry",
        "without a plan",
        "for every occasion",
        "into one backpack",
        "traveling light",
        "together",
      ],
    },
    {
      norm: "To photograph {a} {b}",
      who: "rather photograph {a} {b}",
      a: [
        "every dish",
        "the sunset",
        "the sights",
        "yourself",
        "the cat",
        "the sea",
        "the mountains",
        "the streets",
        "the food",
        "the tickets",
        "the palm trees",
        "the snow",
      ],
      b: [
        "on vacation",
        "every day",
        "without asking",
        "on the beach",
        "from the window",
        "on the train",
        "on the move",
        "in a café",
        "as a keepsake",
        "a hundred times",
      ],
    },
    {
      norm: "To try {a} {b}",
      who: "rather try {a} {b}",
      a: [
        "street food",
        "the local cuisine",
        "exotic fruit",
        "seafood",
        "strange drinks",
        "national dishes",
        "spicy food",
        "desserts",
        "insects",
        "the coffee",
      ],
      b: [
        "at a market",
        "on the first day",
        "on vacation",
        "out of curiosity",
        "on a dare",
        "in a foreign city",
        "for breakfast",
        "on the beach",
        "on a trip",
        "instead of lunch",
      ],
    },
  ],

  friends: [
    {
      norm: "To invite {a} {b}",
      who: "rather invite {a} {b}",
      a: [
        "friends",
        "guests",
        "childhood friends",
        "the neighbors",
        "colleagues",
        "the whole gang",
        "acquaintances",
        "relatives",
        "the partner's friends",
        "the country-house neighbors",
      ],
      b: [
        "for no reason",
        "on a Friday",
        "for dinner",
        "to the country house",
        "for board games",
        "on a weekday",
        "late in the evening",
        "for the weekend",
        "at the last moment",
        "for New Year's",
      ],
    },
    {
      norm: "To cook {a} for {b}",
      who: "rather cook {a} for {b}",
      a: [
        "dinner",
        "a cake",
        "barbecue",
        "pastries",
        "cocktails",
        "pizza",
        "salad",
        "tea",
        "snacks",
        "a pie",
      ],
      b: [
        "friends",
        "the whole gang",
        "colleagues",
        "the neighbors",
        "guests",
        "childhood friends",
        "the parents",
        "the partner",
        "the country-house neighbors",
        "random guests",
      ],
    },
    {
      norm: "To play {a} {b}",
      who: "rather play {a} {b}",
      a: [
        "board games",
        "cards",
        "charades",
        "Mafia",
        "video games",
        "Pictionary",
        "tennis",
        "soccer",
        "hide-and-seek",
        "billiards",
      ],
      b: [
        "until morning",
        "all night",
        "at the country house",
        "with friends",
        "at a party",
        "on a rainy day",
        "on the weekend",
        "as a whole gang",
        "on a dare",
        "to win",
      ],
    },
    {
      norm: "To discuss {a} {b}",
      who: "rather discuss {a} {b}",
      a: [
        "gossip",
        "series",
        "colleagues",
        "other couples",
        "politics",
        "plans",
        "the news",
        "vacation",
        "kids",
        "work",
      ],
      b: [
        "all evening",
        "in the group chat",
        "at dinner",
        "until morning",
        "in the kitchen",
        "in the car",
        "on a walk",
        "in front of everyone",
        "in company",
        "on the phone",
      ],
    },
  ],

  tender: [
    {
      norm: "To hug {a}",
      who: "rather hug you {a}",
      a: [
        "every morning",
        "before bed",
        "after a fight",
        "when you meet",
        "on the couch",
        "in bed",
        "in the kitchen",
        "when saying goodbye",
        "under a blanket",
        "for no reason",
        "while cuddling",
        "after work",
        "at the movies",
        "on a walk",
        "in front of the parents",
        "at dawn",
      ],
    },
    {
      norm: "To say {a} {b}",
      who: "rather say {a} {b}",
      a: [
        "“I love you”",
        "compliments",
        "sweet nothings",
        "“good morning”",
        "“I miss you”",
        "warm words",
        "thank you",
        "“you're the best”",
        "“I'm sorry”",
        "“how are you?”",
      ],
      b: [
        "before bed",
        "every morning",
        "just because",
        "over the phone",
        "in a text message",
        "at breakfast",
        "after work",
        "when saying goodbye",
        "for no reason",
        "in a whisper",
      ],
    },
    {
      norm: "To care for {a}",
      who: "rather care for {a}",
      a: [
        "the partner",
        "the pet",
        "the plants",
        "the parents",
        "the house",
        "the partner's mood",
        "yourself",
        "the tidiness",
        "the guests",
        "the plans",
      ],
    },
    {
      norm: "To make {a} {b}",
      who: "rather make {a} {b}",
      a: [
        "a massage",
        "breakfast",
        "coffee",
        "a surprise",
        "a compliment",
        "a present",
        "a note",
        "a photo",
        "a playlist",
        "a bath",
      ],
      b: [
        "after work",
        "first thing in the morning",
        "for no reason",
        "before bed",
        "on weekends",
        "on a hard day",
        "for an anniversary",
        "in secret",
        "when you meet",
        "instead of words",
      ],
    },
    {
      norm: "To watch {a} together {b}",
      who: "rather watch {a} together {b}",
      a: [
        "series",
        "movies",
        "the sunset",
        "the stars",
        "the sunrise",
        "old photos",
        "cartoons",
        "shows",
        "documentaries",
        "cat videos",
        "fireworks",
        "the rain",
      ],
      b: [
        "while cuddling",
        "before bed",
        "under a blanket",
        "at dinner",
        "on weekends",
        "in bed",
        "on the couch",
        "with tea",
        "in the dark",
        "until morning",
      ],
    },
  ],

  future: [
    {
      norm: "To save up for {a} {b}",
      who: "rather save up for {a} {b}",
      a: [
        "a house",
        "a car",
        "a trip",
        "a wedding",
        "renovation",
        "a country house",
        "education",
        "a pet",
        "a dream",
        "a business",
        "an apartment",
        "a move",
      ],
      b: [
        "together",
        "little by little",
        "from the salary",
        "for years",
        "all at once",
        "in secret",
        "bit by bit",
        "from cashback",
        "as a couple",
        "from the very start",
      ],
    },
    {
      norm: "To plan {a} {b}",
      who: "rather plan {a} {b}",
      a: [
        "a vacation",
        "a move",
        "a wedding",
        "renovation",
        "an apartment purchase",
        "kids",
        "a pet",
        "a business",
        "the country house",
        "a trip",
        "studies",
        "a celebration",
      ],
      b: [
        "a year ahead",
        "together",
        "on the weekend",
        "at dinner",
        "in secret",
        "by horoscope",
        "with the parents",
        "in the kitchen",
        "before bed",
        "while resting",
      ],
    },
    {
      norm: "To dream about {a} {b}",
      who: "rather dream about {a} {b}",
      a: [
        "a house by the sea",
        "a trip around the world",
        "a country house",
        "a dog",
        "kids",
        "a move",
        "a business",
        "traveling",
        "our own garden",
        "a quiet life",
        "a shared home",
        "an old town",
      ],
      b: [
        "together",
        "before bed",
        "in the kitchen",
        "on vacation",
        "just the two of us",
        "at dinner",
        "under the stars",
        "on the road",
        "on long evenings",
        "on a walk",
      ],
    },
    {
      norm: "To wish for {a} {b}",
      who: "rather wish for {a} {b}",
      a: [
        "a wish",
        "a shared goal",
        "a dream",
        "a plan",
        "a date",
        "a tradition",
        "a trip",
        "a purchase",
        "the summer",
        "the future",
      ],
      b: [
        "together",
        "on New Year's",
        "before bed",
        "in secret",
        "under the stars",
        "on a birthday",
        "in the car",
        "at the country house",
        "at dinner",
        "silently",
      ],
    },
  ],

  conflict: [
    {
      norm: "To make up {a}",
      who: "rather make up {a}",
      a: [
        "right away",
        "without words",
        "before bed",
        "the next day",
        "an hour later",
        "over the phone",
        "in a text message",
        "at dinner",
        "with a hug",
        "with a joke",
        "at the door",
        "in silence",
      ],
    },
    {
      norm: "To stay silent {a} {b}",
      who: "rather stay silent {a} {b}",
      a: [
        "all evening",
        "half the day",
        "until morning",
        "all night",
        "until the first word",
        "the whole day",
        "for an hour",
        "for two days",
        "the next day",
        "until the evening",
      ],
      b: [
        "after a fight",
        "over a trifle",
        "out of spite",
        "instead of talking",
        "as a sign of hurt",
        "for no reason",
        "in response",
        "in a quarrel",
        "at home",
        "in front of friends",
      ],
    },
    {
      norm: "To walk away {a} {b}",
      who: "rather walk away {a} {b}",
      a: [
        "to another room",
        "to sleep",
        "for a walk",
        "to the kitchen",
        "to the bathroom",
        "to the balcony",
        "to friends",
        "out of the house",
        "to get some air",
        "into one's shell",
      ],
      b: [
        "after a fight",
        "without answering",
        "mid-argument",
        "in silence",
        "slamming the door",
        "mid-conversation",
        "before making up",
        "for a couple of hours",
        "without saying goodbye",
        "in tears",
      ],
    },
    {
      norm: "To argue {a} {b}",
      who: "rather argue {a} {b}",
      a: [
        "over trifles",
        "about politics",
        "about series",
        "about plans",
        "about money",
        "about food",
        "about tidiness",
        "about the future",
        "about movies",
        "about nothing",
      ],
      b: [
        "all evening",
        "until hoarse",
        "at dinner",
        "in public",
        "in the car",
        "on the phone",
        "in the chat",
        "at home",
        "on a walk",
        "in front of friends",
      ],
    },
  ],
};

/** `either` dilemmas. Pairing within an axis keeps both options comparable. */
export const EITHER_AXES: AxesByTheme = {
  home: [
    {
      label: "The perfect evening at home:",
      options: [
        "a series under a blanket",
        "board games",
        "cooking together",
        "cleaning to music",
        "a bath",
        "video games",
        "reading in silence",
        "ordering food",
        "inviting guests",
        "going to bed at nine",
        "organizing the wardrobe",
        "watching YouTube videos",
        "singing karaoke",
        "walking around the neighborhood",
        "baking something",
      ],
    },
    {
      label: "What matters most in an apartment:",
      options: [
        "a big kitchen",
        "a huge bed",
        "a balcony",
        "underfloor heating",
        "lots of light",
        "a walk-in closet",
        "a bathtub",
        "a workspace",
        "plants",
        "a fireplace",
        "the view from the window",
        "a quiet courtyard",
        "a storage room",
        "a second bathroom",
        "a smart home",
      ],
    },
    {
      label: "A household chore:",
      options: [
        "washing dishes",
        "vacuuming",
        "cooking",
        "doing laundry",
        "taking out the trash",
        "ironing",
        "cleaning up after the pet",
        "washing windows",
        "grocery shopping",
        "dusting",
        "fixing things",
        "paying the utilities",
        "assembling furniture",
        "watering the flowers",
        "changing the bedsheets",
      ],
    },
  ],
  romance: [
    {
      label: "The perfect date:",
      options: [
        "dinner at a restaurant",
        "a walk around the city",
        "a movie",
        "a picnic",
        "a candlelit dinner at home",
        "a concert",
        "a day trip",
        "a museum",
        "a Ferris wheel",
        "coffee at a new café",
        "an escape room",
        "an ice rink",
        "watching the sunset",
        "dancing",
        "a night walk",
      ],
    },
    {
      label: "The best present:",
      options: [
        "flowers",
        "a piece of jewelry",
        "a trip ticket",
        "a book",
        "a matching set",
        "a handmade gift",
        "a massage certificate",
        "a surprise date",
        "a photo album",
        "perfume",
        "a gadget",
        "a warm sweater",
        "a board game",
        "a theater trip",
        "sweets",
      ],
    },
    {
      label: "How to confess your love:",
      options: [
        "in person",
        "over the phone",
        "in a letter",
        "in a text message",
        "with a poem",
        "in public",
        "at sunset",
        "at dinner",
        "as a joke",
        "on a trip",
        "in the rain",
        "at night",
        "on a rooftop",
        "on a date",
        "through a song",
      ],
    },
  ],
  habits: [
    {
      label: "A morning habit:",
      options: [
        "coffee right away",
        "a workout",
        "a shower",
        "scrolling the phone",
        "breakfast",
        "a walk",
        "meditation",
        "getting up last",
        "watching the news",
        "music",
        "cold water",
        "a journal",
        "a plan for the day",
        "hugs",
        "snoozing five times",
      ],
    },
    {
      label: "At eleven p.m. you are:",
      options: [
        "asleep",
        "watching a series",
        "reading",
        "scrolling the feed",
        "eating",
        "tidying up",
        "working",
        "out walking",
        "playing",
        "chatting",
        "listening to music",
        "thinking about life",
        "preparing for tomorrow",
        "in the bath",
        "doing nothing",
      ],
    },
    {
      label: "A weird habit:",
      options: [
        "eating the same breakfast",
        "checking the door",
        "counting stairs",
        "talking to plants",
        "humming out loud",
        "keeping receipts",
        "laying out clothes in advance",
        "sleeping in socks",
        "eating before bed",
        "talking in your sleep",
        "collecting plastic bags",
        "setting an early alarm",
        "watching everything at double speed",
        "eating from one plate",
        "hugging a pillow",
      ],
    },
  ],
  food: [
    {
      label: "Dinner for two:",
      options: [
        "pizza",
        "sushi",
        "pasta",
        "burgers",
        "barbecue",
        "soup",
        "salad",
        "steak",
        "ramen",
        "tacos",
        "paella",
        "borscht",
        "pilaf",
        "a cheese board",
        "ordering delivery",
      ],
    },
    {
      label: "The breakfast of your dreams:",
      options: [
        "an omelet",
        "cottage cheese pancakes",
        "oatmeal",
        "a croissant",
        "avocado toast",
        "pancakes",
        "fried eggs",
        "a sandwich",
        "porridge",
        "granola",
        "coffee with milk",
        "tea",
        "a smoothie",
        "fritters",
        "nothing",
      ],
    },
    {
      label: "What to add to pizza:",
      options: [
        "pineapple",
        "mushrooms",
        "bacon",
        "olives",
        "peppers",
        "onion",
        "chicken",
        "cheese",
        "tomatoes",
        "sausage",
        "spinach",
        "shrimp",
        "jalapeño",
        "an egg",
        "double cheese",
      ],
    },
  ],
  money: [
    {
      label: "What to spend a bonus on:",
      options: [
        "a trip",
        "gadgets",
        "shopping",
        "presents",
        "savings",
        "renovation",
        "a restaurant",
        "a course",
        "a car",
        "furniture",
        "medical care",
        "books",
        "video games",
        "jewelry",
        "nothing",
      ],
    },
    {
      label: "How to run the budget:",
      options: [
        "a spreadsheet",
        "an app",
        "envelopes",
        "a piggy bank",
        "saving first",
        "splitting in half",
        "spending without a plan",
        "cash",
        "a cashback card",
        "counting out loud",
        "skimping on food",
        "not counting",
        "saving for a goal",
        "discussing together",
        "separate accounts",
      ],
    },
    {
      label: "A big purchase:",
      options: [
        "an apartment",
        "a car",
        "gadgets",
        "furniture",
        "renovation",
        "a trip",
        "education",
        "a pet",
        "a wedding",
        "a country house",
        "a business",
        "an investment",
        "a vacation",
        "a present",
        "nothing",
      ],
    },
  ],
  travel: [
    {
      label: "The vacation of your dreams:",
      options: [
        "the sea",
        "the mountains",
        "a city",
        "the country house",
        "a cruise",
        "a tent",
        "an all-inclusive hotel",
        "a road trip",
        "an island",
        "a village",
        "a ski resort",
        "hot springs",
        "a train",
        "another continent",
        "staying home",
      ],
    },
    {
      label: "How you pack for a trip:",
      options: [
        "the day before",
        "a month ahead",
        "at the last moment",
        "from a list",
        "without a list",
        "one backpack",
        "three suitcases",
        "with spares",
        "only the essentials",
        "by the weather",
        "without a plan",
        "strictly by itinerary",
        "with a first-aid kit",
        "with food",
        "forget the passport",
      ],
    },
    {
      label: "On the road you:",
      options: [
        "sleep",
        "read",
        "watch a movie",
        "listen to music",
        "talk",
        "play",
        "eat",
        "take photos",
        "plan",
        "look out the window",
        "meet people",
        "work",
        "keep a journal",
        "play word games",
        "do nothing",
      ],
    },
  ],
  friends: [
    {
      label: "The perfect party:",
      options: [
        "at home",
        "at a bar",
        "at the country house",
        "at a club",
        "karaoke",
        "board games",
        "a picnic",
        "a concert",
        "dinner",
        "a movie",
        "an escape room",
        "bowling",
        "the beach",
        "a trip",
        "quietly together",
      ],
    },
    {
      label: "A weekend with friends:",
      options: [
        "a barbecue",
        "board games",
        "a hike",
        "sports",
        "a movie",
        "a café",
        "the country house",
        "a walk",
        "online games",
        "cooking",
        "a concert",
        "a museum",
        "fishing",
        "shopping",
        "just at home",
      ],
    },
    {
      label: "Your role at a party:",
      options: [
        "the host",
        "the DJ",
        "the cook",
        "the photographer",
        "the dancer",
        "the listener",
        "leaving first",
        "staying to the end",
        "introducing everyone",
        "cleaning up after",
        "joking",
        "singing",
        "pouring drinks",
        "arguing",
        "napping in the corner",
      ],
    },
  ],
  tender: [
    {
      label: "A way to show love:",
      options: [
        "hugs",
        "words",
        "a present",
        "time together",
        "care",
        "a note",
        "a massage",
        "a surprise",
        "cooking",
        "a compliment",
        "a trip",
        "a look",
        "a dance",
        "help",
        "nothing",
      ],
    },
    {
      label: "The best moment together:",
      options: [
        "a morning in bed",
        "a walk",
        "cooking",
        "a movie",
        "a trip",
        "a night talk",
        "a hug",
        "laughter",
        "silence",
        "a dance",
        "a shower",
        "breakfast",
        "a sunset",
        "sleep",
        "a first date",
      ],
    },
    {
      label: "When you are sad, you:",
      options: [
        "hug",
        "talk",
        "stay silent",
        "go for a walk",
        "eat",
        "watch a movie",
        "sleep",
        "listen to music",
        "cry",
        "call",
        "write",
        "sit nearby",
        "joke",
        "do nothing",
        "order food",
      ],
    },
  ],
  future: [
    {
      label: "In ten years you are:",
      options: [
        "in your own house",
        "traveling",
        "with kids",
        "in another city",
        "with a pet",
        "at the same job",
        "running a business",
        "by the sea",
        "in the countryside",
        "in an apartment",
        "just the two of us",
        "with a big family",
        "at the country house",
        "abroad",
        "right where you are now",
      ],
    },
    {
      label: "A shared dream:",
      options: [
        "a house",
        "a trip",
        "a pet",
        "kids",
        "a business",
        "a car",
        "a country house",
        "education",
        "a wedding",
        "renovation",
        "a trip around the world",
        "a garden of our own",
        "a move",
        "a quiet life",
        "nothing",
      ],
    },
    {
      label: "Plans for the year:",
      options: [
        "a trip",
        "renovation",
        "sports",
        "a language",
        "savings",
        "a pet",
        "a wedding",
        "a move",
        "a course",
        "a business",
        "kids",
        "a country house",
        "a car",
        "a hobby",
        "rest",
      ],
    },
  ],
  conflict: [
    {
      label: "How you make up:",
      options: [
        "hugging",
        "talking",
        "a joke",
        "a present",
        "food",
        "a walk",
        "a movie",
        "silence",
        "an apology",
        "a night of sleep",
        "a letter",
        "a call",
        "tears",
        "laughter",
        "time",
      ],
    },
    {
      label: "What drives you crazy in a fight:",
      options: [
        "silence",
        "yelling",
        "blame",
        "“I knew it”",
        "walking away",
        "being ignored",
        "sarcasm",
        "old grudges",
        "dragging friends in",
        "comparisons",
        "“calm down”",
        "door slamming",
        "a phone in hand",
        "“nothing happened”",
        "late-night showdowns",
      ],
    },
    {
      label: "A rule of fighting:",
      options: [
        "never sleep angry",
        "talk right away",
        "give it time",
        "don't yell",
        "don't bring up the past",
        "talk about feelings",
        "don't walk away",
        "hug it out",
        "keep texting",
        "don't drag friends in",
        "don't go silent",
        "settle it today",
        "go for a walk",
        "joke",
        "make up before bed",
      ],
    },
  ],
};
