// GENERATED word list for Wordle (English): 1037 common five-letter words.
// Russian words use "е" in place of "ё". Edit tests/wordle/words.test.ts rules before changing the shape.
export const EN_WORDS: string = `
  about above abuse actor acute admit adopt adult after again agent agree ahead alarm album alert
  alike alive allow alone along alter amber among angel anger angle angry ankle apart apple apply
  apron arena argue arise armor array arrow aside asset atlas attic audio avoid awake award aware
  bacon badge badly bagel baker bases basic basin basis beach beard beast begin being belly below
  bench berry bible bingo birch birth bison black blade blame blank blast blaze bleed blend bless
  blind block blood bloom blush board boast bonus boost booth bound brain brake brand brave bread
  break breed brick bride brief bring broad brook broom brown brush buddy build bunch burst buyer
  cabin cable cadet camel canal candy canoe cargo carol carry carve catch cause cedar cello chain
  chair chalk champ chaos charm chart chase cheap check cheek cheer chess chest chick chief child
  chill chime choir chord chose churn cider cigar civic civil claim clash class clean clear clerk
  click cliff climb cling clock close cloth cloud clown coach coast cobra cocoa color comet comic
  comma coral couch cough could count court cover crack craft crane crash crawl crazy cream creek
  crest crime crisp cross crowd crown crumb crush crust cubic curry curve cycle daily dairy daisy
  dance death debut decay delay delta dense depth derby devil diary digit diner dirty disco ditch
  diver dizzy dodge dolly donor doubt dough dozen draft drain drama drape dread dream dress drift
  drill drink drive drown dryer dusty dwarf dying eager eagle early earth easel eaten edict eight
  elbow elder elect elite ember empty enemy enjoy enter entry envoy epoch equal error essay event
  every exact exile exist extra fable faint fairy faith false fancy fatal fault favor feast fence
  ferry fetch fever fiber field fifth fifty fight filth final finch first flame flash flask fleet
  flesh flint float flock flood floor flora flour fluid flute focus force forge forth forty forum
  found frame frank fraud fresh friar fried front frost fruit fully fungi funny gamma gauge genie
  genre ghost ghoul giant glass globe gloom glory glove going goose gorge grace grade grain grand
  grant grape graph grasp grass grave great greed green greet grief grill grind groan gross group
  grove guard guess guest guide guild guilt habit happy harsh haste hasty hatch haven hazel heart
  heavy hedge hello hence heron hippo hobby holly honey honor horse hotel hound house human humor
  hurry hyena icing ideal igloo image imply index inner input irony issue ivory jelly jerky jewel
  joint joker jolly judge juice juicy jumbo jumpy karma kayak kebab kiosk knack knead kneel knife
  knock koala label labor lance large larva laser latch later laugh layer leach learn lease least
  leave legal lemon level lever light lilac limit linen liner llama lobby local lodge logic loose
  lotus lover lower loyal lucky lunar lunch lyric magic major maker mango manor maple march marsh
  mason match mayor medal media melon mercy merge merit merry metal meter midst might mimic miner
  minor minus mirth mixed model moist money month moose moral motel motor motto mount mouse mouth
  movie muddy mummy music naive naked nanny nasty naval nerve never newly niece night ninja noble
  noise noisy nomad north notch novel nurse nylon oasis occur ocean offer often olive omega onion
  onset opera orbit order organ other ought ounce outer owner oxide ozone paint panel panic paper
  parka party pasta patch patio pause peace peach pearl pecan pedal penny perch petal phase phone
  photo piano piece pilot pinch pitch pivot pixel pizza place plaid plain plane plank plant plate
  plaza plead pluck plumb plume plump plush point poker polar polka porch pouch pound power prank
  prawn press price pride prime print prior prize probe proof proud prove psalm pulse punch pupil
  puppy purse quack quail quake quart queen query quest queue quick quiet quill quilt quirk quite
  quota quote rabbi radar radio raise rally ranch range rapid ratio raven reach react ready realm
  rebel refer reign relax relay relic renew reply resin revel rhino rhyme rider ridge rifle right
  rigid rinse rival river rivet roast robin robot rocky rogue roman rough round route royal rugby
  ruler rumor rural rusty sadly safer saint salad salon salsa salty sandy satin sauce scale scalp
  scare scarf scary scene scent scold scone scoop scope score scout scrap screw scrub sedan seize
  sense serve seven shack shade shady shake shall shame shape share shark sharp shawl sheep sheet
  shelf shell shift shine shiny shirt shock shoot shore short shout shrub siege sight sigma silky
  silly since siren sixth sixty skate skill skirt skull skunk slang slate sleek sleep sleet slice
  slide slime slope sloth small smart smash smell smile smoke snack snail snake sneak sniff snowy
  sober solar solid solve sorry sound south space spade spare spark speak spear speed spell spend
  spice spike spill spine split spoil spoon sport spray squad squid stack staff stage stain stair
  stake stale stamp stand stare start state steak steam steel steep steer stern stick stiff still
  sting stock stone stool store stork storm story stout stove strap straw stray strip stuck study
  stuff style sugar suite sunny super surge sushi swamp swarm swear sweat sweep sweet swell swift
  swing swirl sword syrup table taboo tacit talon tango tapir tarot taste tasty teach teddy tempo
  tenth thank theft theme there thick thief thing think third thorn those three throw thumb tiara
  tidal tiger tight timid tired title toast today token tonic tooth topaz topic torch torso total
  totem touch tough towel tower toxic trace track trade trail train trait trash tread treat trend
  trial tribe trick tried troop trout truce truck truly trump trunk trust truth tulip tumor tunic
  tutor tweet twice twist ultra uncle under unify union unite unity upper upset urban usage usher
  usual utter vague valid value valve vapor vault vegan venom venue verse vicar video vigil vigor
  vinyl viola viral virus visit vista vital vivid vocal vodka voice voter vowel wafer wagon waist
  waltz waste watch water weary weave wedge weigh weird whale wheat wheel where which while white
  whole whose widen widow width wield windy witch witty woman woody world worry worse worst worth
  would wound wrist write wrong yacht yeast yield young youth yummy zebra zesty
`;
